In [1]:
# For this example i am using employee.csv dataset
# Download dataset from
# https://www.kaggle.com/datasets/tawfikelmetwally/employee-dataset/data

In [15]:
# For this example we are using Pandas to load dataset file
# and Numpy for operations

In [53]:
import pandas as pd
import numpy as np

# To stop scientific notation
np.set_printoptions(suppress=True)

In [54]:
# loading dataset
employee_data = pd.read_csv("datasets/Employee.csv")

In [55]:
print(employee_data.iloc[0])

Education                    Bachelors
JoiningYear                       2017
City                         Bangalore
PaymentTier                          3
Age                                 34
Gender                            Male
EverBenched                         No
ExperienceInCurrentDomain            0
LeaveOrNot                           0
Name: 0, dtype: object


In [56]:
print(employee_data.head)

<bound method NDFrame.head of       Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes  

In [57]:
# Convert DataFrame to NumPy ndarray
array_data = employee_data.to_numpy()

In [58]:
print(array_data)

[['Bachelors' 2017 'Bangalore' ... 'No' 0 0]
 ['Bachelors' 2013 'Pune' ... 'No' 3 1]
 ['Bachelors' 2014 'New Delhi' ... 'No' 2 0]
 ...
 ['Masters' 2018 'New Delhi' ... 'No' 5 1]
 ['Bachelors' 2012 'Bangalore' ... 'Yes' 2 0]
 ['Bachelors' 2015 'Bangalore' ... 'Yes' 4 0]]


In [59]:
print(array_data[0])

['Bachelors' 2017 'Bangalore' 3 34 'Male' 'No' 0 0]


In [60]:
# Extract only numaric colums for ML

data = array_data[:,[1,3,4,7]].astype(float)
print(data)

[[2017.    3.   34.    0.]
 [2013.    1.   28.    3.]
 [2014.    3.   38.    2.]
 ...
 [2018.    3.   27.    5.]
 [2012.    3.   30.    2.]
 [2015.    3.   33.    4.]]


In [61]:
# Find min and max

min_vals = data.min(axis=0)
max_vals = data.max(axis=0)
print(min_vals)
print("=========")
print(max_vals)

[2012.    1.   22.    0.]
[2018.    3.   41.    7.]


In [63]:
# Broadcasting
scaled_data = (data - min_vals) / (max_vals - min_vals)
print(scaled_data)

[[0.83333333 1.         0.63157895 0.        ]
 [0.16666667 0.         0.31578947 0.42857143]
 [0.33333333 1.         0.84210526 0.28571429]
 ...
 [1.         1.         0.26315789 0.71428571]
 [0.         1.         0.42105263 0.28571429]
 [0.5        1.         0.57894737 0.57142857]]


In [68]:
# Label the target column

y = array_data[:,-1].astype(int)
print(y)

[0 1 0 ... 1 0 0]
