In [6]:
print("Hello Machine Learning!")

Hello Machine Learning!


In [7]:
import numpy as np
print(np.__version__)

2.3.5


In [8]:
import numpy as np
salary = np.array([3000,4000.45,5000.92])
print(salary)

[3000.   4000.45 5000.92]


In [9]:
marks = np.array([
    [80, 85, 90],   # Student 1
    [70, 75, 88],   # Student 2
    [60, 65, 70]    # Student 3
])
print(marks.shape)

(3, 3)


In [10]:
ratings = np.array([4,5,3,4])
print(ratings.ndim)

1


In [11]:
print(marks.ndim)

2


In [12]:
prices = np.array([100,200,300,400])
discount = prices * 0.9
print(discount)

[ 90. 180. 270. 360.]


In [13]:
salaries = np.array([125000.00,248000.45,184000.00])
new_salaries = salaries + 500
print(new_salaries)

[125500.   248500.45 184500.  ]


In [16]:
sales = np.array([
    [1000,1200,1500],
    [2000,2200,2500],
    [3000,3200,3500]
    ])
# Rows = employees 
# Columns = Months
bonus = np.array([100,200,300])
updated_sales = sales+bonus
print(updated_sales)

[[1100 1400 1800]
 [2100 2400 2800]
 [3100 3400 3800]]
