In [1]:
import numpy as np
print(np.__version__)

2.3.5


In [2]:
data = np.array([10,20,30,40,50])
print(data)

[10 20 30 40 50]


In [3]:
print(data.size)

5


In [4]:
print(data.shape)

(5,)


In [8]:
# Arithmetic Operations
print(data+5)
print(data-5)
print(data*5)
print(data/5)
print(data//5)
print(data**2)
print(data%2)

[15 25 35 45 55]
[ 5 15 25 35 45]
[ 50 100 150 200 250]
[ 2.  4.  6.  8. 10.]
[ 2  4  6  8 10]
[ 100  400  900 1600 2500]
[0 0 0 0 0]


In [9]:
# numpy built in functions
np.sqrt(data)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [10]:
np.exp(data)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [11]:
np.log(data) # Logarithm

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [12]:
np.min(data)

np.int64(10)

In [13]:
np.max(data)

np.int64(50)

In [14]:
np.sum(data)

np.int64(150)

In [15]:
np.mean(data)

np.float64(30.0)

In [17]:
np.median(data)

np.float64(30.0)

In [21]:
np.std(data) # Standard Deviation

np.float64(14.142135623730951)

In [23]:
np.var(data) # Variance (Square of standard deviation)

np.float64(200.0)

In [24]:
np.abs([-10,-20,30])

array([10, 20, 30])

In [29]:
np.round([1.23,1.49,2.5,2.51,3.99])

array([1., 1., 2., 3., 4.])

In [33]:
# Vectorized Operations
price = np.array([100,200,300])
discount = price * 0.5
print(price)
print(discount)
# No Loops
# Fast execution

[100 200 300]
[ 50. 100. 150.]


In [34]:
# Operation between Arrays

salary = np.array([1000,2000,3000])
bonus = np.array([100,200,300])
print(salary)
print(bonus)
total_salary = salary + bonus
print(total_salary)

[1000 2000 3000]
[100 200 300]
[1100 2200 3300]


In [42]:
# Matrix Operations
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Addition")
print(A+B)

print("Multiplication")
print(A*B)

print("Matrix multiplication")
print(np.dot(A,B))

Addition
[[ 6  8]
 [10 12]]
Multiplication
[[ 5 12]
 [21 32]]
Matrix multiplication
[[19 22]
 [43 50]]


In [44]:
data = [10, 100, 1000]
np.log(data)



array([2.30258509, 4.60517019, 6.90775528])