In [1]:
# Write code to import NumPy and print its version.
import numpy as np
print(np.__version__)

2.3.5


In [6]:
# Q3 Create a NumPy array containing:
# 10, 20, 30, 40, 50

data = np.array([10,20,30,40,50])
print(data)
print(type(data))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
# Create a 2D NumPy array:
# [
#  [1,2,3],
#  [4,5,6]
# ]

twod_array  = np.array([[1,2,3],[4,5,6]])
print(twod_array)

[[1 2 3]
 [4 5 6]]


In [13]:
# Create an array of zeros containing 5 elements.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
# Q8 Create an array of ones with shape (3,4).
ones = np.ones((3,4))
print(ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
a = np.array([10,20,30,40])
print(a.shape)
print(a.size)
print(a.ndim)

(4,)
4
1


In [19]:
a = np.array([
[1,2,3],
 	[4,5,6]])
print(a.shape)
print(a.size)
print(a.ndim)

(2, 3)
6
2


In [22]:
# Write code to create: 3 rows. 4 columns using NumPy.
data = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(data)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)


(3, 2)


In [27]:
# Create integer array and print dtype.
data = np.array([10,20,30])
print(data.dtype)

int64


In [29]:
# Q22 Create float array and print dtype.
data = np.array([10.25,20.35,30.45])
print(data.dtype)

float64


In [33]:
data = np.array([10,20,30]).astype(float)
print(data)
print(data.dtype)

[10. 20. 30.]
float64


In [35]:
salary = np.array([30000,40000,50000])
bonus = 2000
total_salary = salary + bonus
print(total_salary)

[32000 42000 52000]


In [45]:
prices = np.array([100,200,300])
discount = prices * 0.10
total = prices - discount
print(total)

[ 90. 180. 270.]


In [40]:
sales = np.array([1000,2000,3000])
double = 2
total_sales = sales * double
print(total_sales)

[2000 4000 6000]


In [44]:
temp = np.array([20,25,30])
inc = 5
temp = temp + inc
print(temp)

[25 30 35]


In [46]:
salary = np.array([
 [1000,1200,1500],
 [2000,2200,2500]
])
bonus = np.array([100])
total_salary = salary + bonus
print(total_salary)

[[1100 1300 1600]
 [2100 2300 2600]]


In [47]:
a = np.array([
 [1,2],
 [3,4]])
b = np.array([10,20])
print(a+b)

[[11 22]
 [13 24]]


In [48]:
a = np.array([
 [1],
 [2],
 [3]
])
b = np.array([10,20])
print(a+b)


[[11 21]
 [12 22]
 [13 23]]


In [51]:
salry = np.array([125000,284000,320000])
bonus = np.array([100])
total_salary = salary + bonus
print(total_salary)

[[1100 1300 1600]
 [2100 2300 2600]]


In [52]:
sales = np.array(
    [
        [1000,2000,3000], # Employee 1
        [1500,2500,3500], # Employee 2
    ]
)
extra = np.array([1.1])
total_sales = sales * extra
print(total_sales)

[[1100. 2200. 3300.]
 [1650. 2750. 3850.]]


In [53]:
sales = np.array([1000,2000,3000])
print(f"Total Sales = {np.sum(sales)}")

Total Sales = 6000


In [57]:
salary = np.array([30000,40000,50000])
print(f"Average is {np.mean(salary)}")

Average is 40000.0


In [59]:
age = np.array([22,34,28,41])
print(f"Maximum Age = {np.max(age)}")

Maximum Age = 41


In [60]:
data = np.array([10,20,30,40,50])
print(f"Variance = {np.var(data)}")

Variance = 200.0


In [61]:
data = np.array([10,20,30,40,50])
print(f"std = {np.std(data)}")

std = 14.142135623730951


In [62]:
data = np.array([10,100,1000])
print(f"Logarithm = {np.log(data)}")

Logarithm = [2.30258509 4.60517019 6.90775528]


In [63]:
ages = np.array([22,34,18,40])

# On all ages
print(ages > 18)

[ True  True False  True]


In [65]:
# Get only values > 18
print(ages[ages>18])

[22 34 40]


In [66]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print(a[[0, 1, 2], [0, 0, 1]])


[1 3 6]


In [2]:
import numpy as np
a = np.array([10, 40, 80, 50, 100])
print(a[a > 50])

[ 80 100]


In [70]:
b = np.array([[5, 5], [4, 5], [16, 4]])
res = b.sum(-1)
print(res)
print([res % 10 == 0])
print(b[res % 10 == 0])

[10  9 20]
[array([ True, False,  True])]
[[ 5  5]
 [16  4]]


In [6]:
# Q48 Given a 2D NumPy array, how would you extract all rows where the sum of elements 
# is greater than a given threshold using boolean indexing? 

data = np.array([[5, 5], [4, 5], [16, 4]])
sum = data.sum(axis=1)
print(f"Sum of all Rows = {sum}")
result = data[sum > 10]
print(result)

Sum of all Rows = [10  9 20]
[[16  4]]


In [11]:
# Q49 How can you select elements from a NumPy array that are even numbers only using advanced indexing? 

numbers = np.array([12,3,44,23,45,22,56,48,99])
print(f"Given Number = {numbers}")
even_numbers = numbers % 2 == 0
print(f"Even Numbers = {numbers[even_numbers]}")

Given Number = [12  3 44 23 45 22 56 48 99]
Even Numbers = [12 44 22 56 48]


In [20]:
# Q50 Given a matrix, how would you extract elements from the main diagonal and anti-diagonal simultaneously? 

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
diagonal = np.diag(matrix)
print(f"Diagonal = {diagonal}")
flip_matrix = np.fliplr(matrix)
anti_diagnoal = np.diag(flip_matrix)
print(f"Anti-Diagonal = {anti_diagnoal}")

Diagonal = [1 5 9]
Anti-Diagonal = [3 5 7]


In [32]:
# Q51 How would you filter rows of a 2D array where the maximum value in each row is divisible by 3? 

data = np.array([[5, 9], [41, 15], [16, 30]])

row_max_values = data.max(axis=1)

result = data[row_max_values % 3 == 0]

print(f"row max values = {row_max_values}")
print(f"divisible by 3 are {result}")


row max values = [ 9 41 30]
divisible by 3 are [[ 5  9]
 [16 30]]


In [38]:
# Q52 How can you replace all negative values in a NumPy array with zero using indexing?

numbers = np.array([12,3,44,23,-45,22,56,48,-99])

numbers[numbers < 0] = 0

print(f"Result = {numbers}")


Result = [12  3 44 23  0 22 56 48  0]


In [44]:
# Q53 Given two arrays a and b, how would you select elements from a where corresponding elements in b are greater than 10? 

a = np.array([12,3,44,23,-45,22,56,48,-99])
b = np.array([19,30,4,230,1,-22,5,480,-99])

result = a[b > 10]
print(f"Result = {result}")


Result = [12  3 23 48]


In [46]:
# Q54 How would you reorder rows of a matrix based on a custom index list using fancy indexing? 

matrix = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

order = [2, 0, 1]
reordered = matrix[order]
print(f"Reordered = {reordered}")

Reordered = [[50 60]
 [10 20]
 [30 40]]


In [54]:
# Q55 How can you extract rows from a matrix where at least one element is greater than the row mean? 

matrix = np.array([
    [10, 20],
    [3, 4],
    [50, 60]
])

mean = matrix.mean(axis=1)

print(f"Mean = {mean}")

mask = (matrix > mean[:, None]).any(axis=1)

print(matrix[mask])

Mean = [15.   3.5 55. ]
[[10 20]
 [ 3  4]
 [50 60]]


In [63]:
# Q56 How would you select elements from a 3D array based on a condition applied to one axis? 

matrix_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

# print(matrix_3d.sum(axis=1))

# print(matrix_3d.sum(axis=1).sum(axis=1))

result = matrix_3d[matrix_3d.sum(axis=1).sum(axis=1) > 10]

print(result)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [65]:
# Q57 Given an array, how would you extract elements whose indices are prime numbers?

numbers = np.array([12,3,44,23,45,22,56,48,99])

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_indices = [i for i in range(len(numbers)) if is_prime(i)]

result = numbers[prime_indices]

print(result)


[44 23 22 48]


In [76]:
# Numpy arange function Examples

import numpy as np

# Only Stop Parameter
arr = np.arange(5) # Just like range() function from python.
print(f" arr = {arr}")

# Start and Stop Parameters
arr = np.arange(2,10) # 2 is start and 10 is Stop
print(f" arr = {arr}")

# Start, Stop and Step Parameter
arr = np.arange(0,20,5) # 0 is start and 20 is Stop and 5 is step
print(f" arr = {arr}")

# Negative Step
arr = np.arange(10,0,-1) 
print(f" arr = {arr}")

# Floating point Step
arr = np.arange(0,1,0.2) 
print(f" arr = {arr}")

# Specify Data Type
arr = np.arange(5,dtype=float)
print(f" arr = {arr}")

 arr = [0 1 2 3 4]
 arr = [2 3 4 5 6 7 8 9]
 arr = [ 0  5 10 15]
 arr = [10  9  8  7  6  5  4  3  2  1]
 arr = [0.  0.2 0.4 0.6 0.8]
 arr = [0. 1. 2. 3. 4.]


In [81]:
# Numpy Reshape function Examples

import numpy as np

arr1d = np.arange(12)
print(f" arr of 1D = {arr1d}")

# Reshaping from 1D -> 2D
arr2d = arr1d.reshape(3,4)
print(f" arr of 2D = {arr2d}")

# Note : total elements must remain the same  3 x 4 = 12 (Original arr1d size is 12)

arr2d = arr1d.reshape(2,6)
print(f" arr of 2D = {arr2d}")

arr2d = arr1d.reshape(4,3)
print(f" arr of 2D = {arr2d}")

 arr of 1D = [ 0  1  2  3  4  5  6  7  8  9 10 11]
 arr of 2D = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 arr of 2D = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
 arr of 2D = [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [84]:
import numpy as np

arr1d = np.arange(12)
print(f" arr of 1D = {arr1d}")

# Reshaping from 1D -> 2D
arr2d = arr1d.reshape(3,-1)
print(f" arr of 2D = {arr2d}")

# Reshaping from 1D -> 2D
arr2d = arr1d.reshape(-1,6)
print(f" arr of 2D = {arr2d}")

 arr of 1D = [ 0  1  2  3  4  5  6  7  8  9 10 11]
 arr of 2D = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 arr of 2D = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [85]:
import numpy as np

arr1d = np.arange(12)
print(f" arr of 1D = {arr1d}")

# Reshaping from 1D -> 2D
arr2d = arr1d.reshape(3,-1)  # allowed
print(f" arr of 2D = {arr2d}")

arr2d = arr1d.reshape(-1,-1)  # Error
print(f" arr of 2D = {arr2d}")

 arr of 1D = [ 0  1  2  3  4  5  6  7  8  9 10 11]
 arr of 2D = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: can only specify one unknown dimension

In [93]:
# Example on 3D Array

import numpy as np

arr1d = np.arange(1,25)
print(f"1D array = {arr1d}")

# Reshaping from 1D -> 3D
arr3d = arr1d.reshape(4,3,2)  # 4 -> Blocks,  3 -> Rows per block,  2 -> Columns per row
print(f"3D array = {arr3d}")

1D array = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
3D array = [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [95]:
# Example on linspace

import numpy as np

arr = np.linspace(0,10,5) # 0 -> Start, 10 -> Stop, 5 -> Num of values
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [96]:
arr = np.linspace(1,100,10)
print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [101]:
# Using Endpoint parameter

arr = np.linspace(0,10,5,endpoint=False)
print(f"With False endpoint = {arr}")

arr = np.linspace(0,10,5,endpoint=True) # By default the endpoint will be True
print(f"With True endpoint = {arr}")

With False endpoint = [0. 2. 4. 6. 8.]
With True endpoint = [ 0.   2.5  5.   7.5 10. ]


In [104]:
# Using dtype parameter

arr = np.linspace(1,10,5,dtype=int)
print(arr)

[ 1  3  5  7 10]


In [115]:
# Examples on np.random

import numpy as np

# Random float between 0 and 1
np.random.rand()

0.03487497197185507

In [116]:
# Ramdom array
np.random.rand(3,2) # 3 Rows 2 Col

array([[0.98619859, 0.1941968 ],
       [0.02970644, 0.99468287],
       [0.77652873, 0.46583705]])

In [117]:
# Random integers
np.random.randint(1,10)

8

In [118]:
# Random integer 1D-array
np.random.randint(1,10,size=5)

array([6, 8, 6, 5, 7])

In [119]:
# Random integer 2D-array
np.random.randint(1,50,(3,3))

array([[27,  8, 22],
       [14, 13, 39],
       [13, 12, 48]])

In [121]:
# Random float with range(uniform)
np.random.uniform(1,10)

8.96735654222631

In [122]:
# Random float 1D-array
np.random.uniform(1,10,size=5)

array([4.19125903, 9.6401704 , 1.69834945, 9.83690367, 4.31320917])

In [128]:
# Random choice
np.random.choice([10,20,30,40,50])

np.int64(40)

In [139]:
# Random choice with size
np.random.choice([10,20,30,40,50,60,70,80,90,100],size=3)

array([40, 40, 10])

In [140]:
# Random choice with replace
np.random.choice([10,20,30,40,50,60,70,80,90,100],size=3,replace=False)

array([60, 80, 20])

In [135]:
# Random with Shuffle
arr = np.array([1,2,3,4,5])
print(f" Array Before Shuffle = {arr}")
np.random.shuffle(arr)
print(f" Array After Shuffle = {arr}")

 Array Before Shuffle = [1 2 3 4 5]
 Array After Shuffle = [4 5 3 1 2]


In [136]:
np.random.rand(5)

array([0.45990748, 0.11738604, 0.58176605, 0.94062492, 0.93230641])

In [138]:
np.random.randn(5)

array([-1.03909084,  0.6828089 ,  0.74805258, -0.01674393, -1.60963858])

In [146]:
# Example on shuffle
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(f" Array Before Shuffle = {arr}")
np.random.shuffle(arr)
print(f" Array After Shuffle = {arr}")
print(f" Original Array = {arr}")

 Array Before Shuffle = [ 10  20  30  40  50  60  70  80  90 100]
 Array After Shuffle = [ 20  80  30  90  40  50  10  70 100  60]
 Original Array = [ 20  80  30  90  40  50  10  70 100  60]


In [147]:
# Example on permutation
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(f" Array Before Shuffle = {arr}")
print(f" Array After Permutation = {np.random.permutation(arr)}")
print(f" Original Array = {arr}")

 Array Before Shuffle = [ 10  20  30  40  50  60  70  80  90 100]
 Array After Permutation = [ 80 100  30  10  20  60  40  50  90  70]
 Original Array = [ 10  20  30  40  50  60  70  80  90 100]


In [150]:
# Numpy Reshape Examples

import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90])
print(f" Original Array = {arr}")

 Original Array = [10 20 30 40 50 60 70 80 90]


In [151]:
# reshape 1D -> 2D
arr.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])